# Generated by Django 4.1.1 on 2022-11-28 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giornalista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('cognome', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='articolo',
            name='giornalista',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articoli', to='news.giornalista'),
        ),
    ]
